[package]
name = "aoc_rust_2020"
version = "0.1.0"
authors = ["RobD6 <robdodd6@googlemail.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1"
itertools = "0.9.0"